apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: NodePort
  selector:
    app: reddit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  