apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit
        image: reddit-fastapi  # Local image name (built inside Minikube)
        imagePullPolicy: Never
        ports:
        - containerPort: 80